import { clamp01 } from './audioMath';

export const CHAPTER_AUDIO_IDS = [
  'ashes-of-home',
  'the-root-vault',
  'vespera-in-black',
  'the-drowned-cathedral',
  'the-silent-orbit',
  'the-memory-forge',
  'crown-of-eidolon',
  'the-root-choir',
] as const;

export type ChapterAudioId = (typeof CHAPTER_AUDIO_IDS)[number];

export interface ChapterAudioProfile {
  readonly id: ChapterAudioId;
  readonly title: string;
  readonly tempo: readonly [stillness: number, combat: number];
  /** Accent groups within one bar. Crown material uses the authored 3 + 3 + 3 + 2 cycle. */
  readonly meter: readonly number[];
  readonly harmony: {
    readonly rootHz: number;
    readonly droneRatios: readonly [number, number, number];
    readonly droneDetune: readonly [number, number, number];
    readonly choirRatios: readonly [number, number, number, number];
    readonly choirDetune: readonly [number, number, number, number];
    readonly formantsHz: readonly [number, number, number, number];
  };
  readonly motif: {
    readonly rootHz: number;
    /** Null entries are authored rests, including the missing notes in the Root Choir. */
    readonly semitones: readonly (number | null)[];
    readonly everyBeats: number;
    readonly durationBeats: number;
    readonly gain: number;
    readonly waveform: OscillatorType;
  };
  readonly ambience: {
    readonly filterType: BiquadFilterType;
    readonly filterHz: number;
    readonly q: number;
    readonly noiseGain: number;
    readonly playbackRate: number;
    readonly machineryHz: number;
    readonly machineryGain: number;
  };
  readonly mix: {
    readonly drone: number;
    readonly choir: number;
    readonly reverb: number;
    readonly filterBaseHz: number;
    readonly filterRangeHz: number;
  };
  readonly percussion: {
    readonly accentHz: number;
    readonly pulseHz: number;
    readonly gain: number;
    readonly subdivisionIntensity: number;
  };
  readonly texture: {
    readonly threshold: number;
    readonly filterHz: number;
    readonly gain: number;
  };
  readonly seed: number;
}

/**
 * Runtime-synthesized score profiles. These contain no sampled or copyrighted media; every voice is
 * generated by the existing oscillator and deterministic-noise graph.
 */
export const CHAPTER_AUDIO_PROFILES = {
  'ashes-of-home': {
    id: 'ashes-of-home',
    title: 'Ashes of Home',
    tempo: [48, 92],
    meter: [4],
    harmony: {
      rootHz: 36.71,
      droneRatios: [1, 1.5, 2],
      droneDetune: [0, -5, 4],
      choirRatios: [3, 4, 4.5, 6],
      choirDetune: [-7, 5, -3, 9],
      formantsHz: [620, 920, 1_320, 1_760],
    },
    motif: {
      rootHz: 146.83,
      semitones: [0, 7, 12],
      everyBeats: 4,
      durationBeats: 2.4,
      gain: 0.055,
      waveform: 'triangle',
    },
    ambience: {
      filterType: 'bandpass',
      filterHz: 420,
      q: 0.28,
      noiseGain: 0.2,
      playbackRate: 0.86,
      machineryHz: 31,
      machineryGain: 0.13,
    },
    mix: { drone: 0.86, choir: 0.38, reverb: 0.84, filterBaseHz: 540, filterRangeHz: 2_700 },
    percussion: { accentHz: 72, pulseHz: 108, gain: 0.8, subdivisionIntensity: 0.72 },
    texture: { threshold: 0.46, filterHz: 1_380, gain: 0.7 },
    seed: 0x61736831,
  },
  'the-root-vault': {
    id: 'the-root-vault',
    title: 'The Root Vault',
    tempo: [42, 78],
    meter: [3, 2],
    harmony: {
      rootHz: 36.71,
      droneRatios: [1, 1.05946, 2],
      droneDetune: [-8, 11, -5],
      choirRatios: [2, 3, 4.2378, 5.3394],
      choirDetune: [-13, 8, -9, 15],
      formantsHz: [410, 690, 980, 1_340],
    },
    motif: {
      rootHz: 146.83,
      semitones: [0, null, 1, -12],
      everyBeats: 5,
      durationBeats: 2.8,
      gain: 0.043,
      waveform: 'sawtooth',
    },
    ambience: {
      filterType: 'lowpass',
      filterHz: 185,
      q: 1.08,
      noiseGain: 0.17,
      playbackRate: 0.72,
      machineryHz: 24,
      machineryGain: 0.16,
    },
    mix: { drone: 1.08, choir: 0.52, reverb: 1.06, filterBaseHz: 380, filterRangeHz: 1_820 },
    percussion: { accentHz: 64, pulseHz: 92, gain: 0.66, subdivisionIntensity: 0.78 },
    texture: { threshold: 0.55, filterHz: 760, gain: 0.54 },
    seed: 0x726f6f32,
  },
  'vespera-in-black': {
    id: 'vespera-in-black',
    title: 'Vespera in Black',
    tempo: [60, 106],
    meter: [4],
    harmony: {
      rootHz: 49,
      droneRatios: [1, 1.5, 2.25],
      droneDetune: [0, -3, 6],
      choirRatios: [2, 3, 4, 4.5],
      choirDetune: [-5, 5, -8, 11],
      formantsHz: [720, 1_060, 1_480, 2_080],
    },
    motif: {
      rootHz: 196,
      semitones: [0, 7, 14, 12],
      everyBeats: 4,
      durationBeats: 1.65,
      gain: 0.051,
      waveform: 'triangle',
    },
    ambience: {
      filterType: 'bandpass',
      filterHz: 720,
      q: 0.46,
      noiseGain: 0.19,
      playbackRate: 1.08,
      machineryHz: 42,
      machineryGain: 0.095,
    },
    mix: { drone: 0.72, choir: 0.65, reverb: 0.92, filterBaseHz: 700, filterRangeHz: 3_200 },
    percussion: { accentHz: 82, pulseHz: 126, gain: 0.94, subdivisionIntensity: 0.62 },
    texture: { threshold: 0.34, filterHz: 1_920, gain: 0.9 },
    seed: 0x76657333,
  },
  'the-drowned-cathedral': {
    id: 'the-drowned-cathedral',
    title: 'The Drowned Cathedral',
    tempo: [52, 96],
    meter: [4],
    harmony: {
      rootHz: 36.71,
      droneRatios: [1, 1.5, 2],
      droneDetune: [0, -7, 5],
      choirRatios: [3, 4, 4.489, 6],
      choirDetune: [-11, 7, -4, 13],
      formantsHz: [740, 1_150, 740, 1_150],
    },
    motif: {
      rootHz: 146.83,
      semitones: [0, 7, 12, 19],
      everyBeats: 4,
      durationBeats: 2.25,
      gain: 0.047,
      waveform: 'sine',
    },
    ambience: {
      filterType: 'bandpass',
      filterHz: 310,
      q: 0.32,
      noiseGain: 0.16,
      playbackRate: 1,
      machineryHz: 28,
      machineryGain: 0.1,
    },
    mix: { drone: 1, choir: 1, reverb: 1, filterBaseHz: 620, filterRangeHz: 2_800 },
    percussion: { accentHz: 76, pulseHz: 104, gain: 1, subdivisionIntensity: 0.72 },
    texture: { threshold: 0.38, filterHz: 880, gain: 1 },
    seed: 0x64726f34,
  },
  'the-silent-orbit': {
    id: 'the-silent-orbit',
    title: 'The Silent Orbit',
    tempo: [46, 88],
    meter: [4],
    harmony: {
      rootHz: 41.2,
      droneRatios: [1, 2, 3],
      droneDetune: [-2, 2, -6],
      choirRatios: [2, 3, 4, 6],
      choirDetune: [-4, 4, -7, 7],
      formantsHz: [340, 580, 920, 1_260],
    },
    motif: {
      rootHz: 164.81,
      semitones: [0, null, 7, 12],
      everyBeats: 4,
      durationBeats: 2.7,
      gain: 0.036,
      waveform: 'sine',
    },
    ambience: {
      filterType: 'bandpass',
      filterHz: 95,
      q: 1.8,
      noiseGain: 0.032,
      playbackRate: 0.58,
      machineryHz: 26,
      machineryGain: 0.19,
    },
    mix: { drone: 0.92, choir: 0.28, reverb: 0.24, filterBaseHz: 310, filterRangeHz: 1_640 },
    percussion: { accentHz: 58, pulseHz: 86, gain: 0.38, subdivisionIntensity: 0.82 },
    texture: { threshold: 0.67, filterHz: 1_420, gain: 0.42 },
    seed: 0x6f726235,
  },
  'the-memory-forge': {
    id: 'the-memory-forge',
    title: 'The Memory Forge',
    tempo: [54, 98],
    meter: [3, 3, 2],
    harmony: {
      rootHz: 49,
      droneRatios: [1, 1.4983, 1.8877],
      droneDetune: [9, -12, 17],
      choirRatios: [2, 2.9966, 3.7755, 5.0397],
      choirDetune: [11, -9, 14, -15],
      formantsHz: [1_150, 740, 1_680, 520],
    },
    motif: {
      rootHz: 196,
      semitones: [7, 0, 12, -1, null],
      everyBeats: 3,
      durationBeats: 2.2,
      gain: 0.044,
      waveform: 'triangle',
    },
    ambience: {
      filterType: 'highpass',
      filterHz: 1_240,
      q: 0.7,
      noiseGain: 0.11,
      playbackRate: 0.91,
      machineryHz: 33,
      machineryGain: 0.08,
    },
    mix: { drone: 0.68, choir: 0.82, reverb: 1.18, filterBaseHz: 480, filterRangeHz: 3_560 },
    percussion: { accentHz: 68, pulseHz: 118, gain: 0.72, subdivisionIntensity: 0.66 },
    texture: { threshold: 0.28, filterHz: 2_480, gain: 1.1 },
    seed: 0x6d656d36,
  },
  'crown-of-eidolon': {
    id: 'crown-of-eidolon',
    title: 'Crown of Eidolon',
    tempo: [66, 118],
    meter: [3, 3, 3, 2],
    harmony: {
      rootHz: 36.71,
      droneRatios: [1, 1.5, 2.25],
      droneDetune: [-3, 3, 0],
      choirRatios: [3, 4, 4.5, 6],
      choirDetune: [-7, 7, -5, 5],
      formantsHz: [740, 1_150, 1_540, 2_180],
    },
    motif: {
      rootHz: 146.83,
      semitones: [0, 7, 12, 19],
      everyBeats: 3,
      durationBeats: 1.35,
      gain: 0.062,
      waveform: 'sawtooth',
    },
    ambience: {
      filterType: 'lowpass',
      filterHz: 260,
      q: 0.58,
      noiseGain: 0.21,
      playbackRate: 0.64,
      machineryHz: 22,
      machineryGain: 0.24,
    },
    mix: { drone: 1.18, choir: 1.2, reverb: 0.66, filterBaseHz: 760, filterRangeHz: 3_640 },
    percussion: { accentHz: 84, pulseHz: 116, gain: 1.18, subdivisionIntensity: 0.54 },
    texture: { threshold: 0.24, filterHz: 1_120, gain: 1.15 },
    seed: 0x63726f37,
  },
  'the-root-choir': {
    id: 'the-root-choir',
    title: 'The Root Choir',
    tempo: [38, 72],
    meter: [3, 3, 3, 2],
    harmony: {
      rootHz: 36.71,
      droneRatios: [1, 1.5, 2.25],
      droneDetune: [0, 0, 0],
      choirRatios: [3, 4, 4.5, 6],
      choirDetune: [-2, 2, -1, 1],
      formantsHz: [740, 1_150, 1_820, 2_440],
    },
    motif: {
      rootHz: 146.83,
      semitones: [0, 7, null, 12, 7, null],
      everyBeats: 3,
      durationBeats: 3.4,
      gain: 0.035,
      waveform: 'sine',
    },
    ambience: {
      filterType: 'bandpass',
      filterHz: 1_050,
      q: 0.24,
      noiseGain: 0.13,
      playbackRate: 0.44,
      machineryHz: 18,
      machineryGain: 0.045,
    },
    mix: { drone: 0.54, choir: 1.34, reverb: 1.22, filterBaseHz: 420, filterRangeHz: 2_280 },
    percussion: { accentHz: 52, pulseHz: 78, gain: 0.24, subdivisionIntensity: 0.9 },
    texture: { threshold: 0.42, filterHz: 2_120, gain: 0.62 },
    seed: 0x63686f38,
  },
} as const satisfies Record<ChapterAudioId, ChapterAudioProfile>;

export const DEFAULT_CHAPTER_AUDIO_ID: ChapterAudioId = 'the-drowned-cathedral';

export function chapterTempo(profile: ChapterAudioProfile, intensity: number): number {
  const energy = clamp01(intensity);
  return profile.tempo[0] + (profile.tempo[1] - profile.tempo[0]) * energy;
}

export function chapterBarLength(profile: ChapterAudioProfile): number {
  return profile.meter.reduce((sum, group) => sum + group, 0);
}

export function isChapterAccent(profile: ChapterAudioProfile, beat: number): boolean {
  const barLength = chapterBarLength(profile);
  if (barLength <= 0) return false;
  const position = ((Math.floor(beat) % barLength) + barLength) % barLength;
  let cursor = 0;
  for (const group of profile.meter) {
    if (position === cursor) return true;
    cursor += group;
  }
  return false;
}

export function chapterMotifFrequency(
  profile: ChapterAudioProfile,
  phraseIndex: number,
): number | null {
  const motif = profile.motif.semitones;
  if (motif.length === 0) return null;
  const index = ((Math.floor(phraseIndex) % motif.length) + motif.length) % motif.length;
  const semitones = motif[index];
  return semitones === null ? null : profile.motif.rootHz * 2 ** (semitones / 12);
}
