import type { BestRun, GameSettings, GameSnapshot } from '../game/types/GameTypes';

export const DEFAULT_SETTINGS: GameSettings = {
  masterVolume: 0.85,
  musicVolume: 0.58,
  effectsVolume: 0.82,
  ambienceVolume: 0.7,
  mouseSensitivity: 0.42,
  gamepadSensitivity: 0.58,
  gamepadDeadzone: 0.18,
  fieldOfView: 68,
  quality: 'high',
  captions: true,
  highContrastReticle: false,
  haptics: true,
  reducedMotion: false,
  reducedFlashes: false,
  cameraShake: 0.55,
  aimAssist: 0.3,
  invertY: false,
};

export const INITIAL_SNAPSHOT: GameSnapshot = {
  screen: 'title',
  loadingProgress: 0,
  health: 100,
  maxHealth: 100,
  shield: 50,
  maxShield: 50,
  ammo: 36,
  magazineSize: 36,
  reserveAmmo: 180,
  weaponName: 'SUNLANCE',
  dashCooldown: 0,
  pulseCooldown: 0,
  perspective: 'third',
  objective: 'BREAK THE THREE SEALS',
  objectiveDetail: 'Find a way out of the Root Vault',
  seals: 0,
  totalSeals: 3,
  enemiesRemaining: 0,
  bossName: null,
  bossHealth: 0,
  bossMaxHealth: 0,
  score: 0,
  multiplier: 1,
  hitMarker: 0,
  damageDirection: null,
  caption: null,
  interactPrompt: null,
  pointerLocked: false,
  inputDevice: 'keyboard',
  selectedUpgrade: null,
  runStats: null,
  fps: 60,
};

export const EMPTY_BEST_RUN: BestRun = {
  score: 0,
  elapsedSeconds: 0,
  rank: 'C',
};
